#!/bin/bash
# hub-push.sh — 从本地采集 agent 上下文，推送到远端设备并创建续接 agent
# 用法: hub-push.sh <target-host> <local-cwd> [--provider <p>] [--model <m>] [--agent-id <id>] [--mode <m>] [--title <t>]
#
# 流程:
#   1. 采集本地上下文（git、memory、TODO）
#   2. 路径映射（local cwd → remote cwd）
#   3. 组装交接 prompt
#   4. 在远端通过 paseo run --host 创建续接 agent
#
# 退出码：0=成功，1=失败
#
# 可测试性：所有 paseo 调用通过 ${PASEO_CMD:-paseo} 注入，便于 mock。

set -uo pipefail

PASEO_CMD="${PASEO_CMD:-paseo}"
SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"

# 默认值
PROVIDER="claude"
MODEL="opus"
MODE="auto"
TITLE="Hub Push Task"
AGENT_ID=""

usage() {
  cat <<'EOF'
用法: hub-push.sh <target-host> <local-cwd> [选项]

位置参数:
  target-host    远端主机（IP 或 host:port；如果是 host:port 直接用 --host）
  local-cwd      本地工作目录（绝对路径）

选项:
  --provider <p>   Provider（默认: claude）
  --model <m>      Model（默认: opus）
  --mode <m>       Paseo mode（默认: auto）
  --agent-id <id>  可选，关联的本地 agent ID（仅用于在 prompt 里写明来源）
  --title <t>      Agent 标题（默认: Hub Push Task）
  -h, --help       显示本帮助

示例:
  hub-push.sh 100.101.57.43 /home/mcdowell/wb/projects/tenant-app
  hub-push.sh 100.101.57.43:6767 /Users/mcdowell/AgentWorkspace --provider codebuddy-code --model deepseek-v4-pro

输出：远端 agent ID
EOF
}

# ---------- 参数解析 ----------

if [ $# -lt 2 ]; then
  usage
  exit 1
fi

TARGET_HOST="$1"
LOCAL_CWD="$2"
shift 2

while [ $# -gt 0 ]; do
  case "$1" in
    --provider) PROVIDER="$2"; shift 2 ;;
    --model) MODEL="$2"; shift 2 ;;
    --mode) MODE="$2"; shift 2 ;;
    --agent-id) AGENT_ID="$2"; shift 2 ;;
    --agent-id=*) AGENT_ID="${1#*=}"; shift ;;
    --title) TITLE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "未知参数: $1" >&2; usage; exit 1 ;;
  esac
done

# ---------- 路径校验 ----------

if [ ! -d "$LOCAL_CWD" ]; then
  echo "错误: 本地目录不存在: $LOCAL_CWD" >&2
  exit 1
fi

# ---------- 路径映射（local → remote）----------

# 规则：cwd 包含 /Users/mcdowell → 远端用 /home/mcdowell（Mac→Hub）
#       cwd 包含 /home/mcdowell  → 远端用 /Users/mcdowell（Hub→Mac）
#       其他路径原样透传
map_path_to_remote() {
  local p="$1"
  if echo "$p" | grep -q "/Users/mcdowell"; then
    echo "$p" | sed 's|/Users/mcdowell|/home/mcdowell|'
  elif echo "$p" | grep -q "/home/mcdowell"; then
    echo "$p" | sed 's|/home/mcdowell|/Users/mcdowell|'
  else
    echo "$p"
  fi
}

REMOTE_CWD=$(map_path_to_remote "$LOCAL_CWD")

# 远端 Paseo host：target-host 已是 host:port 形式 → 直接用；
#                 否则默认拼 :6767
if echo "$TARGET_HOST" | grep -q ':'; then
  REMOTE_PASEO="$TARGET_HOST"
else
  REMOTE_PASEO="${TARGET_HOST}:6767"
fi

# ---------- Step 1: 本地采集 ----------

echo "→ 采集本地上下文: $LOCAL_CWD" >&2

PROJECT_NAME=$(basename "$LOCAL_CWD")
GENERATED=$(date '+%Y-%m-%d %H:%M')

cd "$LOCAL_CWD"

# Git 信息
GIT_BLOCK=""
if [ -d ".git" ]; then
  BRANCH=$(git branch --show-current 2>/dev/null || echo "")
  REMOTE=$(git remote get-url origin 2>/dev/null || echo "")
  HEAD=$(git log --oneline -1 2>/dev/null || echo "")
  DIRTY=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
  WORKTREES=$(git worktree list 2>/dev/null | wc -l | tr -d ' ')
  GIT_BLOCK="Branch: ${BRANCH:-unknown}
Remote: ${REMOTE:-none}
HEAD: ${HEAD:-unknown}
Uncommitted files: ${DIRTY:-0}
Worktrees: ${WORKTREES:-0}"
else
  GIT_BLOCK="(not a git repository)"
fi

# 本地 memory 文件（覆盖两个常见 workspace 根）
MEMORY_FILES=$(find "$HOME/AgentWorkspace/memory" "$HOME/wb/memory" -name '*.md' -type f 2>/dev/null | head -20)

# TODO / 阻塞：从最近修改的 memory 文件里抓"未完成"或"阻塞"段
TODO_BLOCK=""
if [ -n "$MEMORY_FILES" ]; then
  TODO_BLOCK=$(echo "$MEMORY_FILES" | head -5 | xargs grep -lE "阻塞|TODO|未完成|next step" 2>/dev/null | head -3 | while read f; do
    echo "--- $f ---"
    grep -E "阻塞|TODO|未完成|next step" "$f" 2>/dev/null | head -5
  done)
fi

# ---------- Step 2: 组装本地报告 ----------

LOCAL_REPORT=$(cat <<EOF
# Local Context Report — $PROJECT_NAME
Generated: $GENERATED

## Source
- Host: $(hostname)
- CWD: $LOCAL_CWD
- Remote CWD: $REMOTE_CWD
- Agent ID: ${AGENT_ID:-<none>}

## Git
$GIT_BLOCK

## Memory Files
$(if [ -z "$MEMORY_FILES" ]; then echo "(no memory files found)"; else echo "$MEMORY_FILES" | sed 's/^/- /'; fi)

## TODO / Blockers
$(if [ -z "$TODO_BLOCK" ]; then echo "(no explicit TODO/blocker markers found in memory)"; else echo "$TODO_BLOCK"; fi)

---
Report generated by hub-push.sh
EOF
)

# ---------- Step 3: 组装交接 prompt ----------

PROMPT=$(cat <<EOF
# 本地上下文续接

从本地设备推送到远端的 agent 工作上下文：

$LOCAL_REPORT

---

## 远端续接任务

1. 阅读上面的本地上下文报告，了解源 agent 完成了什么、卡在哪里
2. 在远端 cwd \`$REMOTE_CWD\` 继续工作
3. 如果需要从本地拉取额外产物（git pull、rsync memory、scp build），执行后开始

## 关键信息

- 本地主机: $(hostname)
- 本地 cwd: $LOCAL_CWD（远端对应: $REMOTE_CWD）
- Provider/Model: $PROVIDER/$MODEL
- 模式: $MODE

## 重要路径映射

所有路径已从本地形式映射到远端形式（/Users/mcdowell ↔ /home/mcdowell），报告里直接用远端路径即可。
EOF
)

# ---------- Step 4: 远端创建续接 agent ----------

echo "→ 在远端创建续接 agent: $PROVIDER/$MODEL @ $REMOTE_CWD (paseo: $REMOTE_PASEO)" >&2

# 写 prompt 到临时文件，绕开命令行参数转义问题
PROMPT_FILE="/tmp/hub-push-prompt-$$.txt"
echo "$PROMPT" > "$PROMPT_FILE"

RESULT=$($PASEO_CMD run --host "$REMOTE_PASEO" --detach \
  --cwd "$REMOTE_CWD" \
  --provider "$PROVIDER/$MODEL" \
  --mode "$MODE" \
  --title "$TITLE" \
  --prompt-file "$PROMPT_FILE" 2>&1) || RESULT=$($PASEO_CMD run --host "$REMOTE_PASEO" --detach \
  --cwd "$REMOTE_CWD" \
  --provider "$PROVIDER/$MODEL" \
  --mode "$MODE" \
  --title "$TITLE" \
  "\$(cat $PROMPT_FILE)" 2>&1)

rm -f "$PROMPT_FILE"

if echo "$RESULT" | grep -qiE "AGENT ID|created|agent-id|agent_id"; then
  echo "$RESULT" | grep -iE "AGENT ID|created|agent-id|agent_id" | head -3
  echo "✓ 远端续接 agent 已创建" >&2
  exit 0
else
  echo "错误: 远端 agent 创建失败" >&2
  echo "$RESULT" >&2
  exit 1
fi
